### ISSUE TITLE
No output on Pimoroni Pirate hat

### ISSUE THREAD

**Issue by Gurkenpetr** [bablokb/pi-webradio#2] opened 2021-11-16 19:23 UTC
Hey @bablokb! Thanks for all the work that you've done. :-)

I'm using a Pi Zero with a Pimoroni Pirate Hat and followed all the steps as described, I've no problem accessing the server via browser, but the screen on my hat doesn't show anything. What could be the problem?

**Comment by Gurkenpetr** [comment] 2021-11-17 17:19
Hi @bablokb!

I didn't get so much debug data from the manual start (see below), but some data from the systemctl status:

>**pi@raspberrypi:~ $** systemctl status pi-webradio-pirate-audio.service
● pi-webradio-pirate-audio.service - pi-webradio for pirate-audio client
     Loaded: loaded (/etc/systemd/system/pi-webradio-pirate-audio.service; enabled; vendor preset: enabled)
     Active: failed (Result: exit-code) since Tue 2021-11-16 20:25:21 CET; 21h ago
    Process: 267 ExecStart=/usr/local/bin/webradio_pirate_audio.py -q -k -e -o (code=exited, status=217/USER)
   Main PID: 267 (code=exited, status=217/USER)
        CPU: 16ms
> Nov 16 20:25:18 raspberrypi systemd[1]: Started pi-webradio for pirate-audio client.
Nov 16 20:25:18 raspberrypi systemd[267]: pi-webradio-pirate-audio.service: Failed to determine user credentials: No such process
Nov 16 20:25:18 raspberrypi systemd[267]: pi-webradio-pirate-audio.service: Failed at step USER spawning /usr/local/bin/webradio_pirate_audio.py: No such proce>
Nov 16 20:25:21 raspberrypi systemd[1]: pi-webradio-pirate-audio.service: Main process exited, code=exited, status=217/USER
Nov 16 20:25:21 raspberrypi systemd[1]: pi-webradio-pirate-audio.service: Failed with result 'exit-code'.
lines 1-12/12 (END)

>**pi@raspberrypi:~ $** sudo systemctl stop pi-webradio-pirate-audio.service

>**pi@raspberrypi:~ $** /usr/local/bin/webradio_pirate_audio.py -d -k -e -o
[DEBUG 18:09:43] PirateAudio: detected ST7789
[DEBUG 18:09:44] RadioClient: events: <generator object SSEClient.events at 0xb4a37990>
[DEBUG 18:09:44] RadioClient: event-processing activated
200 OK
null
[DEBUG 18:09:44] webradio_cli: no stdin ...
[DEBUG 18:09:44] KeyController: have terminal

The display only showed lots of snowy pixels... ;-)

**Comment by bablokb** [comment] 2021-11-17 17:58
oh no, my fault: please change the user in /etc/systemd/system/pi-webradio-pirate-audio.service from bablokb to pi. Then reboot, this should fix it. I will change the file...

**Comment by bablokb** [comment] 2021-11-17 18:32
fixed with ecd8b561442f43fc1a29b3934d25461a1c04678d

**Comment by Gurkenpetr** [comment] 2021-11-17 18:48
OK! Buttons work, but still no output on the screen. Am I missing something important?

**Comment by bablokb** [comment] 2021-11-18 09:46
I will re-install my zero and test myself and report back.

**Comment by bablokb** [comment] 2021-11-18 18:24
So, I fixed another bug. Please update as described in the readme (the readme here in the repo is slightly more current).

But I suspect you also have a problem with your logo-images. Since the display only supports 240x240 pixels, make sure your logos don't exceed this limit.

I opted against scaling from within the code, because of performance reasons, the logos are static anyhow.

**Comment by Rolgnu100** [comment] 2022-12-23 07:06
Good Morning @bablokb! 
Thank you very much for your good work

I have the same issue. Buttons work, but no logos on the pirate.
My system is raspberry pi zero, raspbian bullseye and a pirate audio hat.
I use your version 0.97
The raspberry has one user. The user is roland. I checked the service files pi-webradio.service and pi-webradio-pirate-audio.service. The user in both files is roland.
I checked the size of the channel-logos. They are all 240x240. When running a test-program for ST7789, they are all presented correctly.
I stopped pi-webradio-pirate-audio.service and startet pi-webradio-pirate-audio.py -d -k -e -o.
The debug info went to Keycontroller: have terminal, but when I press a key, nothing happens, no further debug-logs.
After rebooting and start both services on boot, the situation is once more the same:
Channel switching with pirate keys and listening is possible, but no logos on the pirate.

Do you have any ideas ?

**Comment by bablokb** [comment] 2022-12-23 07:53
I will check this again sometime after Christmas/New Year when I find some time. If I can't reproduce the problem, I might ask you to post one of your logo-files.

BTW: which version of Bullseye are you using?

**Comment by Rolgnu100** [comment] 2022-12-28 06:51
Good morning bablokb,

Thank you for your fast response. 

This is my bullseye version:
PRETTY_NAME="Raspbian GNU/Linux 11 (bullseye)"
NAME="Raspbian GNU/Linux"
VERSION_ID="11"
VERSION="11 (bullseye)"
VERSION_CODENAME=bullseye
ID=raspbian
ID_LIKE=debian
HOME_URL="http://www.raspbian.org/"
SUPPORT_URL="http://www.raspbian.org/RaspbianForums"
BUG_REPORT_URL="http://www.raspbian.org/RaspbianBugs"

And this is one of my files:
![Bayern1](https://user-images.githubusercontent.com/121280587/209770683-8c6d941a-e563-4a8a-8502-2b88296f755a.png)

**Comment by bablokb** [comment] 2022-12-30 16:53
I could reproduce the problem on a fresh install of Bullseye. In fact, it has nothing to do with the logos, the display or the OS-release, it seems to be a python-library issue. I have the same problem with the command line client on a fresh install of OpenSuse. And the pirate-audio-script is just a subclass of the normal cli-client.

So I need additional time to find out the culprit and a suitable workaround. It could be the sseclient lib or maybe even urllib3.

I will keep you updated!

**Comment by bablokb** [comment] 2022-12-30 17:05
seems to be related to this one: https://github.com/mpetazzoni/sseclient/issues/20

I will see if I can create a workaround.

**Comment by Rolgnu100** [comment] 2023-01-01 17:28
Thank you very much, so i look forward and wish good luck for the workaround

**Comment by bablokb** [comment] 2023-01-05 11:57
I just added a commit https://github.com/bablokb/pi-webradio/commit/4d8aa6803a7fc74036b344d19cc8f10980933d44
that fixes the issue for me (on my fresh install with Bullseye and on my OpenSUSE laptop).

The update-procedure in the Readme should do the job for you. Please let me know if this also solves the problem for you.

**Comment by Rolgnu100** [comment] 2023-01-08 08:12
Good Morning,
I just did the update. This also solved the problem for me.
Thank you very much.

**Closed** 2023-01-09 16:09 UTC
